disabled_rules:
  - force_cast
  - force_try

excluded:
  - Carthage

type_body_length:
  - 150 # warning
  - 200 # error

identifier_name:
  allowed_symbols: "_"
  min_length: 2

function_parameter_count: 6

line_length:
  warning: 140
  error: 240
  ignores_comments: true

large_tuple: 3
